# Example 2: Metabolite workflow

This notebook provides insights on how to use the tool if you have list of metabolites.

Datasources or annotators used:
* MolMeD
* KEGG
* CompoundWiki
* AOP-WIKI
* Intact

# Import modules

In [1]:
import os
import pickle

import pandas as pd

from pyBiodatafuse import id_mapper
from pyBiodatafuse.analyzer.summarize import BioGraph
from pyBiodatafuse.annotators import aopwiki, compoundwiki, intact, kegg, molmedb
from pyBiodatafuse.graph import saver
from pyBiodatafuse.utils import combine_sources, create_or_append_to_metadata

# Load list of metabolites/chemicals/compounds

In [2]:
metabolites_of_interest = """100208
10040286
10041551
10025195
5291
6030
1172
1060
8571
697993
21831736
159603
445643
"""

metabolite_list = metabolites_of_interest.split("\n")
len(metabolite_list)

14

In [3]:
data_input = pd.DataFrame(metabolite_list, columns=["identifier"])
data_input.head()

  identifier
0     100208
1   10040286
2   10041551
3   10025195
4       5291

### Entity resolution using BridgeDB

In [4]:
# Create directories
base_dir = os.path.abspath(os.getcwd())
DATA_DIR = os.path.join(base_dir, "data")
EXAMPLE_DIR = os.path.join(DATA_DIR, "metabolite_workflow")

os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(EXAMPLE_DIR, exist_ok=True)

In [5]:
pickle_path = f"{EXAMPLE_DIR}/cmpd_list.pkl"
metadata_path = f"{EXAMPLE_DIR}/cmpd_list_metadata.pkl"

if not os.path.exists(pickle_path):
    bridgedb_df, bridgedb_metadata = id_mapper.bridgedb_xref(
        identifiers=data_input,
        input_species="Human",
        input_datasource="PubChem Compound",
        output_datasource="All",
    )
    bridgedb_df.to_pickle(pickle_path)
    with open(metadata_path, "wb") as file:
        pickle.dump(bridgedb_metadata, file)
else:
    bridgedb_df = pd.read_pickle(pickle_path)
    with open(metadata_path, "rb") as file:
        bridgedb_metadata = pickle.load(file)

In [6]:
print("Number of metabolies with mapping in BridgeDb:", len(bridgedb_df["identifier"].unique()))
bridgedb_df.head()

Number of metabolies with mapping in BridgeDb: 13

  identifier identifier.source                       target     target.source
0     100208  PubChem-compound                        90560        ChemSpider
1     100208  PubChem-compound                       100208  PubChem Compound
2     100208  PubChem-compound                  HMDB0244377              HMDB
3     100208  PubChem-compound  OFDNQWIFNXBECV-UHFFFAOYSA-N          InChIKey
4     100208  PubChem-compound                       C11280     KEGG Compound

### Transporter inhibited from MolMeDB

In [7]:
molmedb_path = f"{EXAMPLE_DIR}/molmedb.pkl"
molmedb_metadata_path = f"{EXAMPLE_DIR}/molmedb_metadata.pkl"

if not os.path.exists(molmedb_path):
    molmedb_transporter_inhibited_df, molmedb_transporter_inhibited_metadata = (
        molmedb.get_compound_gene_inhibitor(bridgedb_df=bridgedb_df)
    )
    molmedb_transporter_inhibited_df.to_pickle(molmedb_path)
    with open(molmedb_metadata_path, "wb") as file:
        pickle.dump(molmedb_transporter_inhibited_metadata, file)
else:
    molmedb_transporter_inhibited_df = pd.read_pickle(molmedb_path)
    with open(molmedb_metadata_path, "rb") as file:
        molmedb_transporter_inhibited_metadata = pickle.load(file)

In [8]:
molmedb_transporter_inhibited_df.head(2)

,identifier,identifier.source,target,target.source,MolMeDB_transporter_inhibited
0,100208,PubChem-compound,OFDNQWIFNXBECV-UHFFFAOYSA-N,InChIKey,[{'MolMeDB_uniprot_trembl_id': 'Uniprot-TrEMBL...
1,10025195,PubChem-compound,LEJRLSZVESQKJK-UHFFFAOYSA-N,InChIKey,"[{'MolMeDB_uniprot_trembl_id': nan, 'MolMeDB_h..."

### AOPs from AOP-Wiki

In [9]:
aopwiki_path = f"{EXAMPLE_DIR}/aopwiki.pkl"
aopwiki_metadata_path = f"{EXAMPLE_DIR}/aopwiki_metadata.pkl"

if not os.path.exists(aopwiki_path):
    aopwiki_df, aopwiki_metadata = aopwiki.get_aops(bridgedb_df=bridgedb_df)
    aopwiki_df.to_pickle(aopwiki_path)
    with open(aopwiki_metadata_path, "wb") as file:
        pickle.dump(aopwiki_metadata, file)
else:
    aopwiki_df = pd.read_pickle(aopwiki_path)
    with open(aopwiki_metadata_path, "rb") as file:
        aopwiki_metadata = pickle.load(file)

In [10]:
aopwiki_df.head(2)

,identifier,identifier.source,target,target.source,AOP_Wiki_RDF_compounds
0,100208,PubChem-compound,100208,PubChem Compound,"[{'aop': nan, 'aop_title': nan, 'MIE_title': n..."
1,10025195,PubChem-compound,10025195,PubChem Compound,"[{'aop': nan, 'aop_title': nan, 'MIE_title': n..."

### Pathways from KEGG

In [11]:
kegg_path = f"{EXAMPLE_DIR}/kegg.pkl"
kegg_metadata_path = f"{EXAMPLE_DIR}/kegg_metadata.pkl"

if not os.path.exists(kegg_path):
    kegg_df, kegg_metadata = kegg.get_pathways(bridgedb_df=bridgedb_df)
    kegg_df.to_pickle(kegg_path)
    with open(kegg_metadata_path, "wb") as file:
        pickle.dump(kegg_metadata, file)
else:
    kegg_df = pd.read_pickle(kegg_path)
    with open(kegg_metadata_path, "rb") as file:
        kegg_metadata = pickle.load(file)

In [12]:
kegg_df.head(2)

,identifier,identifier.source,target,target.source,KEGG_pathways
0,100208,PubChem-compound,C11280,KEGG Compound,"[{'pathway_id': nan, 'pathway_label': nan, 'pa..."
1,6030,PubChem-compound,C00105,KEGG Compound,"[{'pathway_id': 'path:hsa00240', 'pathway_labe..."

### Pathways from CompoundWiki and Intact

In [13]:
intact_path = f"{EXAMPLE_DIR}/intact.pkl"
intact_metadata_path = f"{EXAMPLE_DIR}/intact_metadata.pkl"

if not os.path.exists(intact_path):
    intact_compound_df, intact_compound_metadata = intact.get_compound_interactions(
        bridgedb_df, interaction_type="both"
    )
    intact_compound_df.to_pickle(intact_path)
    with open(intact_metadata_path, "wb") as file:
        pickle.dump(intact_compound_metadata, file)
else:
    intact_compound_df = pd.read_pickle(intact_path)
    with open(intact_metadata_path, "rb") as file:
        intact_compound_metadata = pickle.load(file)

In [14]:
intact_compound_df.head(2)

,identifier,identifier.source,target,target.source,IntAct_compound_interactions
0,10040286,PubChem-compound,CHEBI:91540,ChEBI,"[{'interaction_id': nan, 'interactor_id_A': na..."
1,5291,PubChem-compound,CHEBI:45783,ChEBI,"[{'interaction_id': 'EBI-1380444', 'interactor..."

In [15]:
combined_subset = combine_sources(
    bridgedb_df,
    [
        intact_compound_df,
    ],
)

In [16]:
compoundwiki_path = f"{EXAMPLE_DIR}/compoundwiki.pkl"
compoundwiki_metadata_path = f"{EXAMPLE_DIR}/compoundwiki_metadata.pkl"

if not os.path.exists(compoundwiki_path):
    compoundwiki_df, compoundwiki_metadata = compoundwiki.get_compound_annotations(combined_subset)
    compoundwiki_df.to_pickle(compoundwiki_path)
    with open(compoundwiki_metadata_path, "wb") as file:
        pickle.dump(compoundwiki_metadata, file)
else:
    compoundwiki_df = pd.read_pickle(compoundwiki_path)
    with open(compoundwiki_metadata_path, "rb") as file:
        compoundwiki_metadata = pickle.load(file)

In [17]:
compoundwiki_df.head(2)

,identifier,identifier.source,target,target.source,IntAct_compound_interactions,CompoundWiki_compounds
0,100208,PubChem-compound,100208,PubChem Compound,NaN,"[{'CAS Registry Number': nan, 'ChEBI ID': nan,..."
1,10040286,PubChem-compound,10040286,PubChem Compound,"[{'interaction_id': nan, 'interactor_id_A': na...","[{'CAS Registry Number': nan, 'ChEBI ID': nan,..."

# Create the BDF graph

In [18]:
combined_df = combine_sources(
    bridgedb_df, df_list=[kegg_df, molmedb_transporter_inhibited_df, aopwiki_df, compoundwiki_df]
)
combined_df.head()

,identifier,identifier.source,target,target.source,KEGG_pathways,MolMeDB_transporter_inhibited,AOP_Wiki_RDF_compounds,IntAct_compound_interactions,CompoundWiki_compounds
0,100208,PubChem-compound,100208,PubChem Compound,"[{'pathway_id': nan, 'pathway_label': nan, 'pa...",[{'MolMeDB_uniprot_trembl_id': 'Uniprot-TrEMBL...,"[{'aop': nan, 'aop_title': nan, 'MIE_title': n...",NaN,"[{'CAS Registry Number': nan, 'ChEBI ID': nan,..."
1,10040286,PubChem-compound,10040286,PubChem Compound,NaN,"[{'MolMeDB_uniprot_trembl_id': nan, 'MolMeDB_h...","[{'aop': nan, 'aop_title': nan, 'MIE_title': n...","[{'interaction_id': nan, 'interactor_id_A': na...","[{'CAS Registry Number': nan, 'ChEBI ID': nan,..."
2,10041551,PubChem-compound,10041551,PubChem Compound,NaN,[{'MolMeDB_uniprot_trembl_id': 'Uniprot-TrEMBL...,"[{'aop': nan, 'aop_title': nan, 'MIE_title': n...",NaN,"[{'CAS Registry Number': nan, 'ChEBI ID': nan,..."
3,10025195,PubChem-compound,10025195,PubChem Compound,NaN,"[{'MolMeDB_uniprot_trembl_id': nan, 'MolMeDB_h...","[{'aop': nan, 'aop_title': nan, 'MIE_title': n...",NaN,"[{'CAS Registry Number': nan, 'ChEBI ID': nan,..."
4,5291,PubChem-compound,5291,PubChem Compound,NaN,[{'MolMeDB_uniprot_trembl_id': 'Uniprot-TrEMBL...,"[{'aop': nan, 'aop_title': nan, 'MIE_title': n...","[{'interaction_id': 'EBI-1380444', 'interactor...","[{'CAS Registry Number': nan, 'ChEBI ID': nan,..."

In [19]:
combined_metadata = create_or_append_to_metadata(
    bridgedb_metadata, [kegg_metadata, molmedb_transporter_inhibited_metadata, aopwiki_metadata]
)

# Saving the graph

### Create a graph from the annotated dataframe

In [20]:
from pyBiodatafuse.graph.generator import build_networkx_graph

g = build_networkx_graph(combined_df=combined_df)

Building graph: 100%|██████████| 13/13 [00:00<00:00, 4930.01it/s]

In [21]:
pygraph = saver.save_graph(
    combined_df=combined_df,
    combined_metadata=combined_metadata,
    graph_name="metabolite_workflow",
    graph_dir=DATA_DIR,
)

Combined DataFrame saved in /Users/yojana/Documents/GitHub/pyBiodatafuse/examples/data/metabolite_workflow_df.pkl
Metadata saved in /Users/yojana/Documents/GitHub/pyBiodatafuse/examples/data/metabolite_workflow_metadata.pkl
Building graph: 100%|██████████| 13/13 [00:00<00:00, 6304.31it/s]
Graph is built successfully
Graph saved in:
 /Users/yojana/Documents/GitHub/pyBiodatafuse/examples/data/metabolite_workflow_graph.pkl
 /Users/yojana/Documents/GitHub/pyBiodatafuse/examples/data/metabolite_workflow_graph.gml
Graph saved in /Users/yojana/Documents/GitHub/pyBiodatafuse/examples/data/metabolite_workflow_graph.edgelist

In [22]:
print(pygraph)

MultiDiGraph with 93 nodes and 129 edges

In [23]:
# Check the node types in the graph
import pyBiodatafuse.constants as Cons

node_types = set()
for node, node_data in pygraph.nodes(data=True):
    node_types.add(node_data[Cons.LABEL])

print(node_types)

{'Pathway', 'Key Event', 'Adverse Outcome', 'Molecular Initiating Event', 'Compound', 'Adverse Outcome Pathway', 'Unknown'}

## Loading the graph into cytoscape

This requires the application to be open.

In [24]:
import logging

from pyBiodatafuse.graph import cytoscape

# Disable all logging for py4cytoscape
logging.disable(logging.CRITICAL)  # Disable all logging
cytoscape.load_graph(
    pygraph, network_name="Compound-Graph example"
)  # Load the graph into Cytoscape

Applying default style...
Applying preferred layout

# Graph statistics

In [25]:
graph_obj = BioGraph(graph=pygraph)
graph_obj.graph_summary

'<table>\n<tbody>\n<tr><td>Nodes          </td><td style="text-align: right;"> 93     </td></tr>\n<tr><td>Edges          </td><td style="text-align: right;">129     </td></tr>\n<tr><td>Components     </td><td style="text-align: right;">  9     </td></tr>\n<tr><td>Network Density</td><td style="text-align: right;">  0.0151</td></tr>\n</tbody>\n</table>'

In [26]:
graph_obj.count_nodes_by_data_source(plot=True)

In [27]:
graph_obj.count_edge_by_data_source(plot=True)